"""Version inicial con modulo de consumo flexible

Revision ID: 7373ae307b23
Revises: 
Create Date: 2025-10-26 22:08:29.089163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7373ae307b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_refrigerio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad_total', sa.Integer(), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('casino', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=100), nullable=False),
    sa.Column('comprador', sa.String(length=100), nullable=False),
    sa.Column('casino', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('minimo', sa.Float(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('casino', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('inversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=100), nullable=False),
    sa.Column('comprador', sa.String(length=100), nullable=False),
    sa.Column('casino', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recibo_compra_id', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=100), nullable=False),
    sa.Column('comprador', sa.String(length=100), nullable=False),
    sa.Column('casino', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compra_recibo_compra_id'), ['recibo_compra_id'], unique=False)

    op.create_table('consumo_refrigerio_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumo_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_consumida', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['consumo_id'], ['consumo_refrigerio.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recibo_id', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('pago', sa.Float(), nullable=False),
    sa.Column('cambio', sa.Float(), nullable=False),
    sa.Column('vendedor', sa.String(length=100), nullable=False),
    sa.Column('casino', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_recibo_id'), ['recibo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_recibo_id'))

    op.drop_table('venta')
    op.drop_table('consumo_refrigerio_item')
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compra_recibo_compra_id'))

    op.drop_table('compra')
    op.drop_table('user')
    op.drop_table('inversion')
    op.drop_table('inventario')
    op.drop_table('gasto')
    op.drop_table('consumo_refrigerio')
    # ### end Alembic commands ###
